### ISSUE TITLE
Navis

### ISSUE THREAD

**Issue by vigji** [brainglobe/morphapi#5]
The natverse people mentioned this project https://github.com/schlegelp/navis that seems to be quite overlapping in scope and quite mature. Do you know it already? Have not tested it yet but probably worth considering to deal with such skeleton things without having to reinvent too much stuff? We could even give them a shout and ask if they would be interested in smoothing a brainglobe (and potentially brainrender?) interactivity in/with their code

**Comment by FedeClaudi** [comment]
I hadn't seen it before. I'd be more than happy to use their package instead of morphapi, or merge if they think it'd be useful. 

The main thing that `morhapi` does is fetching data from Mouselight, Allen Cell Types and neurpmorpho.org. It uses `neurom` from the blue brain project to reconstruct the skeletons, but I'm not very happy with either the code or the results. It could be done better for sure, but haven't put too much thoughts into this.

**Comment by vigji** [comment]
Ok, I will explore `navis` a bit more then!

**Comment by adamltyson** [comment]
A very late update, I'm in touch with the navis devs, and hoping to meet in the new year.

**Comment by adamltyson** [comment]
Closing as tracked in https://github.com/brainglobe/BrainGlobe/issues/52
