### ISSUE TITLE
Creating a neuron from SWC fails with some files

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/morphapi#59]
This is based on [this image.sc issue](https://forum.image.sc/t/brainrender-error-when-rendering-my-own-neuron-morphology/95389/1).

This is a summary of @IgorTatarnikov (mostly) and I looking into the problem, but TBH I don't know anything about SWC files. When loading a neuron file with e.g:

```python
from morphapi.morphology.morphology import Neuron
neuron_path = 'swc.swc'
```

Sometimes this error is thrown:
```
Sample id: 1 refers to non-existant parent ID: 0
```

This means that a line in the SWC file has a parent structure (0, which should be "type unknown") that is not defined. It's because [these lines](https://github.com/brainglobe/morphapi/blob/9cd4a8bf19813fd2da4554f634bb9b6ae74ff283/morphapi/morphology/morphology.py#L95-L99) in morphapi are changing the parent structure. This `repair_swc_file` method was added to fix [this issue](https://github.com/BlueBrain/NeuroM/issues/835).

It seems as if in some cases, there is a structure that is having it's parent changed from `-1` to `0` when `0` doesn't exist. 

Some naive solutions:
* Set to the lowest structure value in the file, e.g. `1` for soma? This would presumably add an erroneous connection.
* Add the "unknown" structure somewhere. Would this add an erroneous extra structure somewhere? 
* Just remove the structure rather than changing it? This could be problematic if it's important. 

@adrien-berchet I don't suppose you have any ideas?

**Comment by adrien-berchet** [comment]
Hi @adamltyson 
As far as I can see, there is no reason to keep https://github.com/brainglobe/morphapi/blob/9cd4a8bf19813fd2da4554f634bb9b6ae74ff283/morphapi/morphology/morphology.py#L95-L99 here. If a morphology is not correct it should be fixed by the user, not automatically by the code. Nevertheless, I tried with a more recent version of MorphIO and it is loaded properly (though a warning is raised, so I guess a similar process is now done in MorphIO. So I think it's better to just remove the `repair_swc_file()` function.
